Last stage of testing for version switch fix
Signed-off-by: Alexander J. V. White <git@ajvwhite.com>

diff --git a/sphpf b/sphpf
--- a/sphpf
+++ b/sphpf
@@ -168,28 +168,46 @@ logMsg 7 "Detecting currently active PHP versions (fpm & command line)"
 # Use PHP to determine the current PHP version
 CURRENT_CMDLINE_VERSION=$(php -r "error_reporting(0); echo substr(phpversion(), 0, 3);")
 
-# Use PHP to determine the current PHP version
-CURRENT_FPM_VERSION=$(launchctl list | grep -oE "php(@[0-9]+(.[0-9]+)?)?" | awk "{gsub(/php$/,\"php@$PHP_LATEST_STANDARD_VERSION\")}1" | sort -r)
-if [ ! -z "$CURRENT_FPM_VERSION" ];then
-    CURRENT_FPM_VERSION=${CURRENT_FPM_VERSION//php@/""}
+# Find the list of active PHP FPM services running
+CURRENT_FPM_VERSIONS=$(launchctl list | grep -oE "php(@[0-9]+(.[0-9]+)?)?" | awk "{gsub(/php$/,\"php@$PHP_LATEST_STANDARD_VERSION\")}1" | sort -r)
+CURRENT_FPM_VERSIONS_FLAT=
+if [ ! -z "$CURRENT_FPM_VERSIONS" ];then
+    CURRENT_FPM_VERSIONS=${CURRENT_FPM_VERSIONS//php@/""}
+
+    for phpActiveServiceVersion in ${CURRENT_FPM_VERSIONS//\\n/ }
+    do
+        if [ "$phpActiveServiceVersion" == "$PHP_LATEST_STANDARD_VERSION" ]; then
+            if [ ! -z "$CURRENT_FPM_VERSIONS_FLAT" ]; then
+                CURRENT_FPM_VERSIONS_FLAT="$CURRENT_FPM_VERSIONS_FLAT php"
+            else
+                CURRENT_FPM_VERSIONS_FLAT="php"
+            fi
+        else
+            if [ ! -z "$CURRENT_FPM_VERSIONS_FLAT" ]; then
+                CURRENT_FPM_VERSIONS_FLAT="$CURRENT_FPM_VERSIONS_FLAT php@$phpActiveServiceVersion"
+            else
+                CURRENT_FPM_VERSIONS_FLAT="php@$phpActiveServiceVersion"
+            fi
+        fi
+    done
 fi
 
 if [ -z "$CURRENT_CMDLINE_VERSION" ]; then
     echo "We had trouble detecting the current command line version of PHP, exiting:" 1>&2
     echo "  Command line version: N/A" 1>&2
-    if [ -z "$CURRENT_FPM_VERSION" ]; then
-        echo "  FPM version:          N/A" 1>&2
+    if [ -z "$CURRENT_FPM_VERSIONS" ]; then
+        echo "   FPM services active: N/A" 1>&2
     else
-        echo "  FPM version:          $CURRENT_FPM_VERSION" 1>&2
+        echo "   FPM services active: $CURRENT_FPM_VERSIONS_FLAT" 1>&2
     fi
     exit 1
 fi
 
-if [ "$CURRENT_CMDLINE_VERSION" != "$CURRENT_FPM_VERSION" ];then
-    if [ ! -z "$CURRENT_FPM_VERSION" ]; then
-        logMsg 5 "Command line & FPM versions are out of sync: $CURRENT_CMDLINE_VERSION vs $CURRENT_FPM_VERSION respectively"
+if [ "$CURRENT_CMDLINE_VERSION" != "$CURRENT_FPM_VERSIONS" ];then
+    if [ ! -z "$CURRENT_FPM_VERSIONS" ]; then
+        logMsg 5 "Command line & FPM versions are out of sync: $CURRENT_CMDLINE_VERSION vs PHP-FPM Services active: $CURRENT_FPM_VERSIONS_FLAT respectively"
     else
-        logMsg 5 "Command line & FPM versions are out of sync: $CURRENT_CMDLINE_VERSION vs N/A respectively"
+        logMsg 5 "Command line & FPM versions are out of sync: $CURRENT_CMDLINE_VERSION vs PHP-FPM Services active: N/A respectively"
     fi
 else
     logMsg 7 "Command line and FPM versions are equal"
@@ -206,22 +224,13 @@ fi
 
 logMsg 6 "Found PHP versions:"
 logMsg 6 "  Command line version: $CURRENT_CMDLINE_VERSION"
-if [ -z "$CURRENT_FPM_VERSION" ]; then
-    logMsg 6 "  FPM version:          N/A"
+if [ -z "$CURRENT_FPM_VERSIONS" ]; then
+    logMsg 6 "   FPM services active: N/A"
 else
-    phpMajMinVersionParse $CURRENT_FPM_VERSION CURRENT_FPM_MAJOR CURRENT_FPM_MINOR
-
-    if [ -z "$CURRENT_FPM_MAJOR" ] || [ -z "$CURRENT_FPM_MINOR" ]; then
-        echo "PHP FPM version syntax not recognised!" 1>&2
-        echo
-        showUsage
-        exit 2
-    fi
-
-    logMsg 6 "  FPM version:          $CURRENT_FPM_VERSION"
+    logMsg 6 "   FPM services active: $CURRENT_FPM_VERSIONS_FLAT"
 fi
 
-if [ "$CURRENT_CMDLINE_VERSION" = "$TARGET_PHP_VERSION" ] && [ "$CURRENT_FPM_VERSION" = "$TARGET_PHP_VERSION" ];then
+if [ "$CURRENT_CMDLINE_VERSION" = "$TARGET_PHP_VERSION" ] && [ "$CURRENT_FPM_VERSIONS" = "$TARGET_PHP_VERSION" ];then
     echo "Detected that target version is already active."
     echo
     while true; do
@@ -233,12 +242,47 @@ if [ "$CURRENT_CMDLINE_VERSION" = "$TARGET_PHP_VERSION" ] && [ "$CURRENT_FPM_VER
     done
 fi
 
-exit 0;
+if [ ! -z "$CURRENT_FPM_VERSIONS" ];then
+    logMsg 6 "Stopping current PHP FPM services..."
+    for phpServiceVersion in ${CURRENT_FPM_VERSIONS//\\n/ }
+    do
+        if [ "$phpServiceVersion" == "$PHP_LATEST_STANDARD_VERSION" ]; then
+            if [ $DO_DRY_RUN -eq 1 ];then
+                echo "brew services stop \"php\""
+            else
+                if ! brew services stop "php" >/dev/null 2>&1; then
+                    logMsg 4 "Failed to stop service php"
+                else
+                    logMsg 6 "Successfully stopped service php"
+                fi
+            fi
+        else
+            if [ $DO_DRY_RUN -eq 1 ];then
+                echo "brew services stop \"php@$phpServiceVersion\""
+            else
+                if ! brew services stop "php@$phpServiceVersion" >/dev/null 2>&1; then
+                    logMsg 4 "Failed to stop service php@$phpServiceVersion"
+                else
+                    logMsg 6 "Successfully stopped service php@$phpServiceVersion"
+                fi
+            fi
+        fi
+    done
+fi
 
 declare -a CURRENT_PHP_PACKAGES
 declare -a TARGET_PHP_PACKAGES
-CURRENT_PHP_PACKAGES=($(brew list | grep php$CURRENT_CMDLINE_VERSION))
-TARGET_PHP_PACKAGES=($(brew list | grep php$TARGET_PHP_VERSION))
+if [ "$CURRENT_CMDLINE_VERSION" == "$PHP_LATEST_STANDARD_VERSION" ]; then
+    CURRENT_PHP_PACKAGES=($(brew list | grep -E "php[^@]*$"))
+else
+    CURRENT_PHP_PACKAGES=($(brew list | grep "php@$CURRENT_CMDLINE_VERSION"))
+fi
+
+if [ "$TARGET_PHP_VERSION" == "$PHP_LATEST_STANDARD_VERSION" ]; then
+    TARGET_PHP_PACKAGES=($(brew list | grep -E "php[^@]*$"))
+else
+    TARGET_PHP_PACKAGES=($(brew list | grep "php@$TARGET_PHP_VERSION"))
+fi
 
 packages_to_unlink=$(IFS=' '; echo "${CURRENT_PHP_PACKAGES[*]}")
 packages_to_link=$(IFS=' '; echo "${TARGET_PHP_PACKAGES[*]}")
@@ -266,95 +310,26 @@ else
     fi
 fi
 
-CUR_PHP_FPM_PLIST_NAME=
-CUR_PHP_FPM_PLIST_LINK=
-if [ ! -z "$CURRENT_FPM_VERSION" ]; then
-    CUR_PHP_FPM_PLIST_NAME="homebrew.mxcl.php$CURRENT_FPM_VERSION.plist"
-    CUR_PHP_FPM_PLIST_LINK="$LAUNCHAGENTS_DIR/$CUR_PHP_FPM_PLIST_NAME"
-    logMsg 7 "Current PHP plist location determined as:"
-    logMsg 7 "  $CUR_PHP_FPM_PLIST_LINK"
-fi
-
-TARGET_PHP_FPM_PLIST_NAME="homebrew.mxcl.php$TARGET_PHP_VERSION.plist"
-TARGET_PHP_FPM_PLIST_LINK="$LAUNCHAGENTS_DIR/$TARGET_PHP_FPM_PLIST_NAME"
-logMsg 7 "Target PHP plist destination determined as:"
-logMsg 7 "  $TARGET_PHP_FPM_PLIST_LINK"
-
-TARGET_PHP_FPM_PLIST_FILE_SOURCE="/usr/local/opt/php$TARGET_PHP_VERSION/$TARGET_PHP_FPM_PLIST_NAME"
-logMsg 7 "Target PHP source plist location determined as:"
-logMsg 7 "  $TARGET_PHP_FPM_PLIST_FILE_SOURCE"
-
-if [ ! -f $TARGET_PHP_FPM_PLIST_FILE_SOURCE ];then
-    echo "The source plink for the target PHP version ($TARGET_PHP_VERSION) couldn't be found! Expected:" 1>&2
-    echo "  $TARGET_PHP_FPM_PLIST_FILE_SOURCE" 1>&2
-    echo "Can not continue!" 1>&2
-    exit 1
-fi
-
-if [ ! -z "$CUR_PHP_FPM_PLIST_LINK" ];then
+logMsg 6 "Starting target PHP FPM service."
+if [ "$TARGET_PHP_VERSION" == "$PHP_LATEST_STANDARD_VERSION" ]; then
     if [ $DO_DRY_RUN -eq 1 ];then
-        echo "launchctl unload -w \"$CUR_PHP_FPM_PLIST_LINK\""
+        echo "brew services start \"php\""
     else
-        if ! launchctl unload -w "$CUR_PHP_FPM_PLIST_LINK" >/dev/null 2>&1; then
-            echo "The current PHP FPM service could not be unloaded from:" 1>&2
-            echo "  $CUR_PHP_FPM_PLIST_LINK" 1>&2
-            echo "Please do it manually and try again." 1>&2
-            exit 1
+        if ! brew services start "php" >/dev/null 2>&1; then
+            logMsg 4 "Failed to start service php"
         else
-            logMsg 6 "Unlinked current PHP FPM service file:"
-            logMsg 6 "  $CUR_PHP_FPM_PLIST_LINK"
+            logMsg 6 "Successfully started service php"
         fi
     fi
-fi
-
-logMsg 7 "Clearing all old PHP FPM plists as a precaution before continuing."
-if [ $DO_DRY_RUN -eq 1 ];then
-    echo "rm -f $LAUNCHAGENTS_DIR/homebrew.mxcl.php*.plist"
 else
-    if ! rm -f $LAUNCHAGENTS_DIR/homebrew.mxcl.php*.plist >/dev/null 2>&1; then
-        logMsg 5 "Run of cleanup command: "
-        logMsg 5 "  rm -f $LAUNCHAGENTS_DIR/homebrew.mxcl.php*.plist"
-        logMsg 5 "Failed, this is non critical, but worth being aware of."
+    if [ $DO_DRY_RUN -eq 1 ];then
+        echo "brew services start \"php@$TARGET_PHP_VERSION\""
     else
-        logMsg 6 "Cleanup of old PHP FPM plists complete."
-    fi
-fi
-
-logMsg 6 "Linking new PHP FPM plist."
-if [ $DO_DRY_RUN -eq 1 ];then
-    echo "ln -s \"$TARGET_PHP_FPM_PLIST_FILE_SOURCE\" \"$TARGET_PHP_FPM_PLIST_LINK\""
-else
-    if ! ln -s "$TARGET_PHP_FPM_PLIST_FILE_SOURCE" "$TARGET_PHP_FPM_PLIST_LINK" >/dev/null 2>&1; then
-        echo "The target PHP FPM service plist could not be symlinked from:" 1>&2
-        echo "  $TARGET_PHP_FPM_PLIST_FILE_SOURCE" 1>&2
-        echo "To:" 1>&2
-        echo "  $TARGET_PHP_FPM_PLIST_LINK" 1>&2
-        echo "Exiting." 1>&2
-        exit 1
-    else
-        logMsg 7 "Target PHP FPM service plist symlinked from:"
-        logMsg 7 "  $TARGET_PHP_FPM_PLIST_FILE_SOURCE"
-        logMsg 7 "To:"
-        logMsg 7 "  $TARGET_PHP_FPM_PLIST_LINK"
-    fi
-fi
-
-logMsg 6 "Loading new PHP FPM service."
-if [ $DO_DRY_RUN -eq 1 ];then
-    echo "launchctl load -w \"$TARGET_PHP_FPM_PLIST_LINK\""
-else
-    if ! launchctl load -w "$TARGET_PHP_FPM_PLIST_LINK" >/dev/null 2>&1; then
-        echo "The new PHP FPM service plist could not be loaded from:" 1>&2
-        echo "  $TARGET_PHP_FPM_PLIST_LINK" 1>&2
-        echo "Using:" 1>&2
-        echo "  launchctl load -w \"$TARGET_PHP_FPM_PLIST_LINK\"" 1>&2
-        echo "This was the last step in the process, so you could try it again." 1>&2
-        exit 1
-    else
-        logMsg 7 "The new PHP FPM service plist was loaded from:"
-        logMsg 7 "  $TARGET_PHP_FPM_PLIST_LINK"
-        logMsg 7 "Using:"
-        logMsg 7 "  launchctl load -w \"$TARGET_PHP_FPM_PLIST_LINK\""
+        if ! brew services start "php@$TARGET_PHP_VERSION" >/dev/null 2>&1; then
+            logMsg 4 "Failed to start service php@$TARGET_PHP_VERSION"
+        else
+            logMsg 6 "Successfully started service php@$TARGET_PHP_VERSION"
+        fi
     fi
 fi
 
